version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: "driver"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
    open-pull-requests-limit: 10
