# smoelius: `dylint_driver` is in its own workspace because it requires specific Rust components.

[workspace]
members = [
    "building",
    "cargo-dylint",
    # "driver",
    "dylint",
    "dylint-link",
    "env",
    "examples",
    "utils/linting",
    "utils/testing",
]
