[package]
name = "examples"
version = "2.1.1"
description = "A dummy package for testing the example Dylint libraries"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
dylint_internal = { version = "=2.1.1", path = "../internal", features = ["examples"] }
