[package]
name = "dylint_linting"
version = "0.1.0-pre.7"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utiltities for writing Dylint libraries"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"
